/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    variants: Variant;
    prices: Price;
    pages: Page;
    drops: Drop;
    promos: Promo;
    leads: Lead;
    orders: Order;
    'order-items': OrderItem;
    redirects: Redirect;
    exports: Export;
    imports: Import;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    prices: PricesSelect<false> | PricesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    drops: DropsSelect<false> | DropsSelect<true>;
    promos: PromosSelect<false> | PromosSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'order-items': OrderItemsSelect<false> | OrderItemsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'checkout-messages': CheckoutMessage;
    'cookie-bar': CookieBar;
    'home-page': HomePage;
    navigation: Navigation;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'checkout-messages': CheckoutMessagesSelect<false> | CheckoutMessagesSelect<true>;
    'cookie-bar': CookieBarSelect<false> | CookieBarSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('admin' | 'brand_manager' | 'marketing' | 'operations' | 'sales')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  tag?: ('product' | 'blog' | 'gallery_prints' | 'drops' | 'misc') | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  /**
   * Используется на /<slug> landing page. Пусто = страница не используется как landing.
   */
  h1?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  /**
   * Используется для фильтрации в ProductCardsBlock
   */
  productType?: string | null;
  faqSet?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  bodyContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  /**
   * Если включено — рендерится на /<slug>. Иначе категория только для tagging.
   */
  isLanding?: boolean | null;
  parent?: (number | null) | Category;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  slug: string;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  type: 'tshirt' | 'hoodie' | 'longsleeve' | 'sweatshirt' | 'cap' | 'totebag';
  category?: (number | null) | Category;
  channels: ('b2c' | 'b2b')[];
  printMethods?: ('dtg' | 'dtf' | 'silkscreen' | 'embroidery' | 'thermo')[] | null;
  status: 'draft' | 'published' | 'archived';
  coverMedia?: (number | null) | Media;
  galleryMedia?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  editorViews?: {
    frontView?: (number | null) | Media;
    backView?: (number | null) | Media;
    lsleeveView?: (number | null) | Media;
    rsleeveView?: (number | null) | Media;
  };
  shippingParams?: {
    weight?: number | null;
    width?: number | null;
    length?: number | null;
    depth?: number | null;
  };
  friendsProducts?:
    | {
        product: number | Product;
        id?: string | null;
      }[]
    | null;
  isSale?: boolean | null;
  isForPrinting?: boolean | null;
  color?: string | null;
  stageColor?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  product: number | Product;
  size: string;
  color?: string | null;
  sku: string;
  stockQty: number;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prices".
 */
export interface Price {
  id: number;
  variant: number | Variant;
  currency: 'RUB';
  amount: number;
  validFrom?: string | null;
  validUntil?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  pageType: 'blog' | 'landing';
  subtitle?: string | null;
  cover?: (number | null) | Media;
  author?: string | null;
  hashtags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Сохраняется как есть и рендерится через dangerouslySetInnerHTML. Используется только если body пустой.
   */
  bodyHtml?: string | null;
  likes?: number | null;
  /**
   * Заполняется ETL-скриптом. Для новых постов — null.
   */
  legacyPostId?: number | null;
  publishedAt?: string | null;
  /**
   * Cashback-уровни. Используется только на странице /loyalty.
   */
  loyaltyLevels?:
    | {
        level: string;
        sum: string;
        cashback?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Sequential steps. Используется только на странице /howto.
   */
  howtoSteps?:
    | {
        title: string;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Размерные таблицы для типов одежды. Используется только на странице /size_chart.
   */
  sizeChartItems?:
    | {
        type: string;
        label?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drops".
 */
export interface Drop {
  id: number;
  name: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverMedia?: (number | null) | Media;
  releaseAt?: string | null;
  products?:
    | {
        product: number | Product;
        id?: string | null;
      }[]
    | null;
  status: 'teaser' | 'live' | 'sold_out' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promos".
 */
export interface Promo {
  id: number;
  code: string;
  discountType: 'percent' | 'fixed';
  discountValue: number;
  validFrom?: string | null;
  validUntil?: string | null;
  usageLimit?: number | null;
  usageCount?: number | null;
  appliesTo?:
    | {
        product: number | Product;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Архив лидов до перехода на @payloadcms/plugin-form-builder. Новые submissions падают в коллекцию Form Submissions (группа Forms). Эта коллекция read-only — кнопка Create скрыта, но существующие записи доступны для просмотра/обработки/удаления.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  comment?: string | null;
  referenceUrl?: string | null;
  source: 'footer' | 'popup' | 'shop-no-model' | 'product-page' | 'methods-consultation' | 'checkout';
  /**
   * Cookie roistat_visit, для трекинга источника
   */
  roistatVisit?: string | null;
  userAgent?: string | null;
  attachments?:
    | {
        side?: string | null;
        url: string;
        filename?: string | null;
        id?: string | null;
      }[]
    | null;
  status: 'new' | 'contacted' | 'done' | 'spam';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * PNHD-YYYYMMDD-NNNN (auto-generated)
   */
  orderNumber?: string | null;
  channel: 'b2c' | 'b2b';
  customer: {
    name: string;
    phone: string;
    email?: string | null;
    note?: string | null;
    roistatVisit?: string | null;
  };
  delivery?: {
    type?: ('cdek_pvz' | 'cdek_door' | 'self_pickup') | null;
    cityCode?: string | null;
    cityName?: string | null;
    address?: string | null;
    pvzCode?: string | null;
    cost?: number | null;
  };
  promoCode?: (number | null) | Promo;
  subtotal: number;
  discount?: number | null;
  shippingCost?: number | null;
  total: number;
  status: 'draft' | 'pending_payment' | 'paid' | 'in_production' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
  paymentStatus: 'unpaid' | 'awaiting_callback' | 'paid' | 'failed' | 'refunded';
  productionStatus?: ('not_started' | 'layout_review' | 'printing' | 'qc' | 'packed') | null;
  /**
   * Заполняется Phase 5 hook (СБП Tochka/T-Bank — отложено)
   */
  paymentProvider?: ('tochka' | 'tbank') | null;
  sbpQrId?: string | null;
  sbpQrUrl?: string | null;
  /**
   * Заполняется Phase 6 hook (КОМТЕТ Касса — отложено)
   */
  fiscalReceiptId?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items".
 */
export interface OrderItem {
  id: number;
  order: number | Order;
  product: number | Product;
  variant: number | Variant;
  quantity: number;
  pricePerUnit: number;
  printConfig?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lineTotal: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Перенаправления URL. From — старый путь (например /old-product). To — внутренний документ или внешний URL. Применяется через middleware на storefront.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'products';
          value: number | Product;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: number;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  ipHash?: string | null;
  userAgent?: string | null;
  bitrixLeadId?: string | null;
  bitrixError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'createCollectionExport' | 'createCollectionImport' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'createCollectionExport' | 'createCollectionImport' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'prices';
        value: number | Price;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'drops';
        value: number | Drop;
      } | null)
    | ({
        relationTo: 'promos';
        value: number | Promo;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'order-items';
        value: number | OrderItem;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  tag?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  h1?: T;
  metaTitle?: T;
  metaDescription?: T;
  productType?: T;
  faqSet?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  bodyContent?: T;
  heroImage?: T;
  isLanding?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  description?: T;
  type?: T;
  category?: T;
  channels?: T;
  printMethods?: T;
  status?: T;
  coverMedia?: T;
  galleryMedia?:
    | T
    | {
        image?: T;
        id?: T;
      };
  editorViews?:
    | T
    | {
        frontView?: T;
        backView?: T;
        lsleeveView?: T;
        rsleeveView?: T;
      };
  shippingParams?:
    | T
    | {
        weight?: T;
        width?: T;
        length?: T;
        depth?: T;
      };
  friendsProducts?:
    | T
    | {
        product?: T;
        id?: T;
      };
  isSale?: T;
  isForPrinting?: T;
  color?: T;
  stageColor?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  product?: T;
  size?: T;
  color?: T;
  sku?: T;
  stockQty?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prices_select".
 */
export interface PricesSelect<T extends boolean = true> {
  variant?: T;
  currency?: T;
  amount?: T;
  validFrom?: T;
  validUntil?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pageType?: T;
  subtitle?: T;
  cover?: T;
  author?: T;
  hashtags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  body?: T;
  bodyHtml?: T;
  likes?: T;
  legacyPostId?: T;
  publishedAt?: T;
  loyaltyLevels?:
    | T
    | {
        level?: T;
        sum?: T;
        cashback?: T;
        label?: T;
        id?: T;
      };
  howtoSteps?:
    | T
    | {
        title?: T;
        body?: T;
        image?: T;
        id?: T;
      };
  sizeChartItems?:
    | T
    | {
        type?: T;
        label?: T;
        image?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drops_select".
 */
export interface DropsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  coverMedia?: T;
  releaseAt?: T;
  products?:
    | T
    | {
        product?: T;
        id?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promos_select".
 */
export interface PromosSelect<T extends boolean = true> {
  code?: T;
  discountType?: T;
  discountValue?: T;
  validFrom?: T;
  validUntil?: T;
  usageLimit?: T;
  usageCount?: T;
  appliesTo?:
    | T
    | {
        product?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  comment?: T;
  referenceUrl?: T;
  source?: T;
  roistatVisit?: T;
  userAgent?: T;
  attachments?:
    | T
    | {
        side?: T;
        url?: T;
        filename?: T;
        id?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  channel?: T;
  customer?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
        note?: T;
        roistatVisit?: T;
      };
  delivery?:
    | T
    | {
        type?: T;
        cityCode?: T;
        cityName?: T;
        address?: T;
        pvzCode?: T;
        cost?: T;
      };
  promoCode?: T;
  subtotal?: T;
  discount?: T;
  shippingCost?: T;
  total?: T;
  status?: T;
  paymentStatus?: T;
  productionStatus?: T;
  paymentProvider?: T;
  sbpQrId?: T;
  sbpQrUrl?: T;
  fiscalReceiptId?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items_select".
 */
export interface OrderItemsSelect<T extends boolean = true> {
  order?: T;
  product?: T;
  variant?: T;
  quantity?: T;
  pricePerUnit?: T;
  printConfig?: T;
  lineTotal?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  ipHash?: T;
  userAgent?: T;
  bitrixLeadId?: T;
  bitrixError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Тексты для корзины, чекаута и страницы благодарности. Меняем wording без редеплоя.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checkout-messages".
 */
export interface CheckoutMessage {
  id: number;
  cartPageTitle: string;
  cartManagerDisclaimer?: string | null;
  checkoutSubmitLabel: string;
  checkoutDisclaimer?: string | null;
  thanksHeading: string;
  thanksBody: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  thanksCallbackPromiseMinutes?: number | null;
  thanksCTAs?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Текст и кнопка cookie-уведомления. excludedRoutes (на каких страницах не показывать) — захардкожены в коде.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-bar".
 */
export interface CookieBar {
  id: number;
  enabled?: boolean | null;
  title: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  buttonLabel: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Главная страница сайта. Блоки можно перетаскивать для изменения порядка. Каждый блок — своя секция с настраиваемым содержимым.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  sections?:
    | (
        | {
            rotatingTitles?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            methodsList?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            featureBullets?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            showLoyaltyBanner?: boolean | null;
            loyaltyEyebrow?: string | null;
            loyaltyTitle?: string | null;
            loyaltyHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            sectionTitle?: string | null;
            subtitle?: string | null;
            items?:
              | {
                  title: string;
                  href: string;
                  bgColor: string;
                  color: 'black' | 'white';
                  image?: (number | null) | Media;
                  imageSlug?: ('tshirt' | 'sweatshirt' | 'hoodie' | 'pullover' | 'totebag' | 'cap') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'category-grid';
          }
        | {
            sectionTitle?: string | null;
            sectionSubtitle?: string | null;
            /**
             * Если оставлено пустым — рендерятся все 5 методов. Например "shelkografiya" чтобы скрыть шелкографию.
             */
            excludedSlugs?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'methods-list';
          }
        | {
            sectionTitle?: string | null;
            ctaHref?: string | null;
            items?:
              | {
                  title: string;
                  text: string;
                  image?: (number | null) | Media;
                  imageSlug?: ('stage1' | 'stage2' | 'stage3' | 'stage4') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stages';
          }
        | {
            sectionTitle?: string | null;
            sectionSubtitle?: string | null;
            mainBlockText?: string | null;
            mainBlockCtaLabel?: string | null;
            mainBlockPopupTitle?: string | null;
            sideInfoText?: string | null;
            rows?:
              | {
                  method: string;
                  /**
                   * Если пусто — рендерим "Стоимость". Для DTG обычно "На белом / цветном", для ВЫШИВКА — "Стоимость (от 10 штук)".
                   */
                  caption?: string | null;
                  cells?:
                    | {
                        format: string;
                        price: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing-table';
          }
        | {
            title: string;
            /**
             * Если заголовок содержит этот фрагмент — он будет визуально выделен. Если пусто — заголовок целиком.
             */
            highlight?: string | null;
            subtitle?: string | null;
            items?:
              | {
                  title: string;
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'about';
          }
        | {
            sectionTitle?: string | null;
            ratingValue?: string | null;
            ratingText?: string | null;
            yandexUrl?: string | null;
            googleUrl?: string | null;
            items?:
              | {
                  author: string;
                  text: string;
                  rating?: number | null;
                  photo?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            sectionTitle?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            eyebrow?: string | null;
            title: string;
            subtitle?: string | null;
            description?: string | null;
            ctaLabel: string;
            ctaHref: string;
            isExternal?: boolean | null;
            variant?: ('shop' | 'form' | 'generic') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Единый список пунктов меню для шапки / подвала / мобильного меню. Visibility-флаги контролируют где элемент показывается. Порядок в массиве = порядок отображения.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  items?:
    | {
        label: string;
        /**
         * Внутренние: /shop, /contacts. Внешние: https://… (поставь isExternal).
         */
        href: string;
        /**
         * Опционально: например feedback → /?#feedback
         */
        hash?: string | null;
        isExternal?: boolean | null;
        showInHeader?: boolean | null;
        showInFooter?: boolean | null;
        showInMobile?: boolean | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Контактные данные, лейблы CTA, аналитика и social-ссылки. Видно на каждой странице сайта.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  businessHours: string;
  /**
   * Формат для schema.org openingHours. businessHours выше — для display в шапке.
   */
  openingHours: string;
  phone: string;
  siteName: string;
  legalName: string;
  inn: string;
  kpp: string;
  copyrightStartYear: string;
  contacts: {
    email: string;
    address: {
      street: string;
      locality: string;
      postalCode: string;
      country: string;
    };
  };
  /**
   * Координаты для schema.org GeoCoordinates. Использовать [yandex.maps.ru](https://yandex.ru/maps) → правый клик → "Что здесь?" для получения точки.
   */
  geo: {
    latitude: number;
    longitude: number;
  };
  headerCTALabel: string;
  mobileCTALabel: string;
  defaultPopupTitle: string;
  madeinRussiaLabel?: string | null;
  madeinRussiaEnabled?: boolean | null;
  wholesaleUrl: string;
  social?: {
    telegramUrl?: string | null;
    telegramLabel?: string | null;
    whatsappUrl?: string | null;
    whatsappLabel?: string | null;
    maxUrl?: string | null;
    maxLabel?: string | null;
  };
  /**
   * IDs сторонних трекеров. Пусто = не подключать.
   */
  analytics?: {
    roistatId?: string | null;
    yandexMetricaId?: string | null;
    uiscomKey?: string | null;
    yandexVerification?: string | null;
  };
  seo?: {
    defaultOGImage?: (number | null) | Media;
    siteLang?: ('ru' | 'en') | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checkout-messages_select".
 */
export interface CheckoutMessagesSelect<T extends boolean = true> {
  cartPageTitle?: T;
  cartManagerDisclaimer?: T;
  checkoutSubmitLabel?: T;
  checkoutDisclaimer?: T;
  thanksHeading?: T;
  thanksBody?: T;
  thanksCallbackPromiseMinutes?: T;
  thanksCTAs?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-bar_select".
 */
export interface CookieBarSelect<T extends boolean = true> {
  enabled?: T;
  title?: T;
  description?: T;
  buttonLabel?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              rotatingTitles?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              methodsList?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              featureBullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              ctaLabel?: T;
              ctaHref?: T;
              showLoyaltyBanner?: T;
              loyaltyEyebrow?: T;
              loyaltyTitle?: T;
              loyaltyHref?: T;
              id?: T;
              blockName?: T;
            };
        'category-grid'?:
          | T
          | {
              sectionTitle?: T;
              subtitle?: T;
              items?:
                | T
                | {
                    title?: T;
                    href?: T;
                    bgColor?: T;
                    color?: T;
                    image?: T;
                    imageSlug?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'methods-list'?:
          | T
          | {
              sectionTitle?: T;
              sectionSubtitle?: T;
              excludedSlugs?: T;
              id?: T;
              blockName?: T;
            };
        stages?:
          | T
          | {
              sectionTitle?: T;
              ctaHref?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    image?: T;
                    imageSlug?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'pricing-table'?:
          | T
          | {
              sectionTitle?: T;
              sectionSubtitle?: T;
              mainBlockText?: T;
              mainBlockCtaLabel?: T;
              mainBlockPopupTitle?: T;
              sideInfoText?: T;
              rows?:
                | T
                | {
                    method?: T;
                    caption?: T;
                    cells?:
                      | T
                      | {
                          format?: T;
                          price?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        about?:
          | T
          | {
              title?: T;
              highlight?: T;
              subtitle?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              sectionTitle?: T;
              ratingValue?: T;
              ratingText?: T;
              yandexUrl?: T;
              googleUrl?: T;
              items?:
                | T
                | {
                    author?: T;
                    text?: T;
                    rating?: T;
                    photo?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              sectionTitle?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              subtitle?: T;
              description?: T;
              ctaLabel?: T;
              ctaHref?: T;
              isExternal?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        hash?: T;
        isExternal?: T;
        showInHeader?: T;
        showInFooter?: T;
        showInMobile?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  businessHours?: T;
  openingHours?: T;
  phone?: T;
  siteName?: T;
  legalName?: T;
  inn?: T;
  kpp?: T;
  copyrightStartYear?: T;
  contacts?:
    | T
    | {
        email?: T;
        address?:
          | T
          | {
              street?: T;
              locality?: T;
              postalCode?: T;
              country?: T;
            };
      };
  geo?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  headerCTALabel?: T;
  mobileCTALabel?: T;
  defaultPopupTitle?: T;
  madeinRussiaLabel?: T;
  madeinRussiaEnabled?: T;
  wholesaleUrl?: T;
  social?:
    | T
    | {
        telegramUrl?: T;
        telegramLabel?: T;
        whatsappUrl?: T;
        whatsappLabel?: T;
        maxUrl?: T;
        maxLabel?: T;
      };
  analytics?:
    | T
    | {
        roistatId?: T;
        yandexMetricaId?: T;
        uiscomKey?: T;
        yandexVerification?: T;
      };
  seo?:
    | T
    | {
        defaultOGImage?: T;
        siteLang?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | 'users'
      | 'media'
      | 'categories'
      | 'products'
      | 'variants'
      | 'prices'
      | 'pages'
      | 'drops'
      | 'promos'
      | 'leads'
      | 'orders'
      | 'order-items'
      | 'redirects'
      | 'exports'
      | 'imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'categories';
          value: number | Category;
        } | null)
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null);
    global?: ('checkout-messages' | 'cookie-bar' | 'home-page' | 'navigation' | 'site-settings') | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}